# Generated by Django 3.2.20 on 2023-07-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=7)),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
